title: "Baymine's Blog"
description: "Data Engineer sharing thoughts on technology, programming, and life"
url: "https://baymine.github.io"
baseurl: ""

author:
  name: "York Cao"
  bio: "Data Engineer based in Beijing"
  location: "Beijing, China"
  github: "Baymine"

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Enhanced Kramdown settings for better markdown support
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
    span:
      line_numbers: false
  math_engine: katex
  math_engine_opts:
    preview: true
    preview_as_code: false

# Rouge syntax highlighting settings
rouge:
  default_lang: console
  css_class: 'highlight'
  span:
    line_numbers: false
  block:
    line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num/"

theme: minima
